### ISSUE TITLE
E484: Can't open file /Users/vheon/.hariti/setup.vim

### ISSUE THREAD

**Issue by vheon** [kamichidu/vim-hariti#2]
I wanted to try vim-hariti and did the following:
- I commented out the vim-plug setup
- added

```
if has('vim_starting')
set runtimepath+=$HOME/.hariti/bundle/vim-hariti/
runtime plugin/hariti.vim
endif
```

to the vimrc

then

```
mkdir -p ~/.hariti/bundle
cd ~/.hariti/bundle
git clone https://github.com/kamichidu/vim-hariti
```

and when starting vim I got this errors:

```
Building ...
function hariti#loader#load..hariti#builder#build..<SNR>5_parse, line 2
hariti: No such file `/Users/vheon/.hariti/bundles'
Error detected while processing function hariti#loader#load:
line   11:
E484: Can't open file /Users/vheon/.hariti/setup.vim
```

**Comment by kamichidu** [comment]
Thanks for trying.

It error means there's no bundles file, default is ~/.hariti/bundles
This plugin requires its file for installing other plugins.

See my bundles file:
https://github.com/kamichidu/dotfiles/blob/master/bundles

**Comment by vheon** [comment]
I think that a better error message should be given to the user, don't you think? Plus why don't you just create an empty one if it is not found?

**Comment by kamichidu** [comment]
fmm... I think Plug and this  are different.
I agree with you thus, will change a message ex. ''Should write bundles file ~/.hariti/bundles''

**Comment by kamichidu** [comment]
Sorry, I've reset master.
Re-open this.

**Comment by kamichidu** [comment]
When there's no bundles file, hariti run with empty bundles.
This is similar to concrete empty bundles file.

Thanks for your suggestion!
